version: '3.8'

services:
  web:
    build: .
    container_name: justhost-web
    ports:
      - "8000:8000"
    depends_on:
      - justhost-postgres-database

  justhost-postgres-database:
    image: postgres:17-alpine
    container_name: justhost-postgres-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assignment
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
