# Generated by Django 5.1.5 on 2025-01-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('cpu', models.PositiveIntegerField()),
                ('ram', models.PositiveIntegerField()),
                ('hdd', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('blocked', 'Blocked'), ('stopped', 'Stopped')], max_length=10)),
            ],
            options={
                'verbose_name': 'VPS Server',
                'verbose_name_plural': 'VPS Servers',
                'db_table': 'vps_servers',
                'ordering': ('status',),
            },
        ),
    ]
